// Code generated by "stringer -type=Operate -output vao_operate_string.go"; DO NOT EDIT.

package mongoex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OperateNil-1]
	_ = x[OperateEq-100100]
	_ = x[OperateNe-100101]
	_ = x[OperateGt-100102]
	_ = x[OperateGte-100103]
	_ = x[OperateLt-100104]
	_ = x[OperateLte-100105]
	_ = x[OperateIn-100106]
	_ = x[OperateNin-100107]
	_ = x[OperateAnd-100200]
	_ = x[OperateOr-100201]
	_ = x[OperateNot-100202]
	_ = x[OperateNor-100203]
	_ = x[OperateExists-100300]
	_ = x[OperateType-100301]
	_ = x[OperateAll-100400]
	_ = x[OperateElemMatch-100401]
	_ = x[OperateSize-100402]
	_ = x[OperateRegex-100500]
	_ = x[OperateText-100501]
	_ = x[OperateWhere-100502]
	_ = x[OperateNear-100503]
	_ = x[OperateGeoWithin-100504]
	_ = x[OperateSum-200100]
	_ = x[OperateAvg-200101]
	_ = x[OperateMin-200102]
	_ = x[OperateMax-200103]
	_ = x[OperatePush-200104]
	_ = x[OperateAddToSet-200105]
	_ = x[OperateFirst-200106]
	_ = x[OperateLast-200107]
	_ = x[OperateProject-300100]
	_ = x[OperateMatch-300101]
	_ = x[OperateLimit-300102]
	_ = x[OperateSkip-300103]
	_ = x[OperateUnwind-300104]
	_ = x[OperateGroup-300105]
	_ = x[OperateSort-300106]
	_ = x[OperateGeoNear-300107]
}

const (
	_Operate_name_0 = "OperateNil"
	_Operate_name_1 = "OperateEqOperateNeOperateGtOperateGteOperateLtOperateLteOperateInOperateNin"
	_Operate_name_2 = "OperateAndOperateOrOperateNotOperateNor"
	_Operate_name_3 = "OperateExistsOperateType"
	_Operate_name_4 = "OperateAllOperateElemMatchOperateSize"
	_Operate_name_5 = "OperateRegexOperateTextOperateWhereOperateNearOperateGeoWithin"
	_Operate_name_6 = "OperateSumOperateAvgOperateMinOperateMaxOperatePushOperateAddToSetOperateFirstOperateLast"
	_Operate_name_7 = "OperateProjectOperateMatchOperateLimitOperateSkipOperateUnwindOperateGroupOperateSortOperateGeoNear"
)

var (
	_Operate_index_1 = [...]uint8{0, 9, 18, 27, 37, 46, 56, 65, 75}
	_Operate_index_2 = [...]uint8{0, 10, 19, 29, 39}
	_Operate_index_3 = [...]uint8{0, 13, 24}
	_Operate_index_4 = [...]uint8{0, 10, 26, 37}
	_Operate_index_5 = [...]uint8{0, 12, 23, 35, 46, 62}
	_Operate_index_6 = [...]uint8{0, 10, 20, 30, 40, 51, 66, 78, 89}
	_Operate_index_7 = [...]uint8{0, 14, 26, 38, 49, 62, 74, 85, 99}
)

func (i Operate) String() string {
	switch {
	case i == 1:
		return _Operate_name_0
	case 100100 <= i && i <= 100107:
		i -= 100100
		return _Operate_name_1[_Operate_index_1[i]:_Operate_index_1[i+1]]
	case 100200 <= i && i <= 100203:
		i -= 100200
		return _Operate_name_2[_Operate_index_2[i]:_Operate_index_2[i+1]]
	case 100300 <= i && i <= 100301:
		i -= 100300
		return _Operate_name_3[_Operate_index_3[i]:_Operate_index_3[i+1]]
	case 100400 <= i && i <= 100402:
		i -= 100400
		return _Operate_name_4[_Operate_index_4[i]:_Operate_index_4[i+1]]
	case 100500 <= i && i <= 100504:
		i -= 100500
		return _Operate_name_5[_Operate_index_5[i]:_Operate_index_5[i+1]]
	case 200100 <= i && i <= 200107:
		i -= 200100
		return _Operate_name_6[_Operate_index_6[i]:_Operate_index_6[i+1]]
	case 300100 <= i && i <= 300107:
		i -= 300100
		return _Operate_name_7[_Operate_index_7[i]:_Operate_index_7[i+1]]
	default:
		return "Operate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
